### PR TITLE
update gifsicle source and linux x64 to v1.92 #104

### PR DESCRIPTION
**Pull request by mreinstein**
@XhmikosR I updated the linux x64 build manually. This is important for AWS lambda, because it's not possible to run npm install in that environment. This ensures the linux binary that ships with the package is up to date and usable there. 

Let me know if you have any questions/issues, happy to make changes to get this published.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Not sure about this. You are basically removing the linux binary.

/CC @sindresorhus

I will update the Windows binaries soon.

**Comment by mreinstein** [comment]
> You are basically removing the linux binary.

I'm not sure I understand, can you clarify? As far as I can tell the linux binary is still present, it's just 11.7 kb smaller: 

https://github.com/imagemin/gifsicle-bin/pull/106/commits/5dab1ad95833958ec50221be61edbc33165dc616

AWS Lambda is kind of a special case because unlike the other linux platforms, you can't run `npm install gifsicle` on it, so the `postinstall` hook won't run which takes care of building the binary.

Open for suggestions though, if we want to handle this a different way.

**Comment by XhmikosR** [comment]
Ah, yeah you are right, the binary is there just smaller.

**Comment by mreinstein** [comment]
in the same vein, https://github.com/imagemin/pngquant-bin/pull/102

**Comment by janwidmer** [comment]
Any update when this might get merged? With version `5.0.0` our build does not work in CI anymore as the linux bin is missing..

**Comment by 1000ch** [comment]
Sorry for the too delayed reply.

@mreinstein Thank you for your efforts. could you please fix the conflicts? (or @alexander-akait?)

**Comment by mreinstein** [comment]
@1000ch all good, I know we're all busy with stuff. 👍 

Given it's been almost 2 years since I submitted this patch, I'm not super familiar with the details. I can refresh my memory and submit a fresh PR, will you prioritize getting this merged if I take the time to do that?

**Comment by mreinstein** [comment]
@1000ch closing this one in favor of #118  (the fresh PR you requested.)

**Pull request closed without merging**
